services:
  wol-service:
    build: .
    network_mode: host
    environment:
      TARGET_MAC_ADDRESSES: ${TARGET_MAC_ADDRESSES} #  <MAC1>,<MAC2>,<MAC3>
    volumes:
      - wol_data:/data  # Mount the volume to /data
    restart: unless-stopped

  # Optional Caddy for TLS
  #caddy:
  #  image: caddy:2
  #  network_mode: host
  #  ports:
  #    - "80:80"   # HTTP
  #    - "443:443"  # HTTPS
  #  volumes:
  #    - ./Caddyfile:/etc/caddy/Caddyfile
  #    - caddy_data:/data
  #    - caddy_config:/config
  #  depends_on:
  #    - wol-service

volumes:
  wol_data: # Declare the volume